spring:
  datasource:
   username : root
   password : lih6662688
   url : jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=ture
   driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-location: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.mapper